[paths]
data = "examples/two_eq_lag.csv"
log_out = "log/two_eq_lag.log"
#prior_dist = "theta_two_eq_lag.csv"

[config]
cycles = 1000
engine = "NPAG"
init_points = 1000
seed = 347
tui = false
pmetrics_outputs = true
parameter_names=[" Ka","Ke ","V_max","lag"]

[randfix]
KPC = 2.0

[constant]
KCP = 3.0